name: Build Android Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Set up Node.js (LTS Version)
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*' # This will use the latest LTS version of Node.js
      - name: Yarn install
        run: yarn
      - name: Build Android Release
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
          cd android && ./gradlew assembleRelease
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app-release
          path: android/app/build/outputs/apk/release/app-release.apk
